import {
    Code,
    Palette,
    Globe,
    FileText,
    Video,
    Smartphone,
    Network,
    Gamepad2Icon as GameController2,
    Shield,
    Brain,
    Wrench,
    Monitor,
    Box,
} from "lucide-react"

export interface ProgramDetail {
    name: string
    description: string
    officialUrl?: string
    logoUrl: string
    icon: any // Keep for fallback
    color: string
    category: string
}

// Map subject IDs to their required programs with full details
export const programsBySubject: Record<string, ProgramDetail[]> = {
    "it-support": [
        {
            name: "osTicket",
            description: "نظام تذاكر الدعم الفني مفتوح المصدر",
            officialUrl: "https://osticket.com",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/OsTicket_logo.png/640px-OsTicket_logo.png",
            icon: Wrench,
            color: "bg-blue-50 text-blue-600 dark:bg-blue-900/20 dark:text-blue-300",
            category: "support",
        },
        {
            name: "VMware",
            description: "برامج الأجهزة الافتراضية",
            officialUrl: "https://www.vmware.com",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Vmware.svg/2560px-Vmware.svg.png",
            icon: Monitor,
            color: "bg-orange-50 text-orange-600 dark:bg-orange-900/20 dark:text-orange-300",
            category: "virtualization",
        },
    ],
    "data-modeling": [
        {
            name: "Microsoft Excel",
            description: "برنامج جداول البيانات والحسابات المتقدم",
            officialUrl: "https://www.microsoft.com/excel",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Microsoft_Office_Excel_%282019%E2%80%93present%29.svg/1101px-Microsoft_Office_Excel_%282019%E2%80%93present%29.svg.png",
            icon: FileText,
            color: "bg-green-50 text-green-600 dark:bg-green-900/20 dark:text-green-300",
            category: "office",
        },
        {
            name: "Microsoft Access",
            description: "نظام إدارة قواعد البيانات",
            officialUrl: "https://www.microsoft.com/access",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Microsoft_Office_Access_%282019%E2%80%93present%29.svg/1200px-Microsoft_Office_Access_%282019%E2%80%93present%29.svg.png",
            icon: FileText,
            color: "bg-red-50 text-red-600 dark:bg-red-900/20 dark:text-red-300",
            category: "database",
        },
        {
            name: "Power BI",
            description: "أداة تحليل وتصور البيانات",
            officialUrl: "https://powerbi.microsoft.com",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Microsoft_Power_BI_Logo.svg/1200px-Microsoft_Power_BI_Logo.svg.png",
            icon: FileText,
            color: "bg-yellow-50 text-yellow-600 dark:bg-yellow-900/20 dark:text-yellow-300",
            category: "analytics",
        },
    ],
    "networks-intro": [
        {
            name: "Cisco Packet Tracer",
            description: "محاكي الشبكات لتعلم أساسيات الشبكات",
            officialUrl: "https://www.netacad.com/courses/packet-tracer",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/CISCO_LOGO.svg/1200px-CISCO_LOGO.svg.png",
            icon: Network,
            color: "bg-cyan-50 text-cyan-600 dark:bg-cyan-900/20 dark:text-cyan-300",
            category: "network",
        },
        {
            name: "Wireshark",
            description: "أداة تحليل بروتوكولات الشبكة",
            officialUrl: "https://www.wireshark.org",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Wireshark_icon.svg/1200px-Wireshark_icon.svg.png",
            icon: Network,
            color: "bg-blue-50 text-blue-600 dark:bg-blue-900/20 dark:text-blue-300",
            category: "network",
        },
    ],
    "programming-intro": [
        {
            name: "Visual Studio Code",
            description: "محرر أكواد متقدم ومجاني",
            officialUrl: "https://code.visualstudio.com",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png",
            icon: Code,
            color: "bg-blue-50 text-blue-600 dark:bg-blue-900/20 dark:text-blue-300",
            category: "programming",
        },
        {
            name: "Python",
            description: "لغة برمجة سهلة التعلم ومتعددة الاستخدامات",
            officialUrl: "https://www.python.org",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1869px-Python-logo-notext.svg.png",
            icon: Code,
            color: "bg-yellow-50 text-yellow-600 dark:bg-yellow-900/20 dark:text-yellow-300",
            category: "programming",
        },
    ],
    "digital-graphics": [
        {
            name: "GIMP",
            description: "برنامج تحرير الصور المجاني",
            officialUrl: "https://www.gimp.org",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/The_GIMP_icon_-_gnome.svg/1024px-The_GIMP_icon_-_gnome.svg.png",
            icon: Palette,
            color: "bg-orange-50 text-orange-600 dark:bg-orange-900/20 dark:text-orange-300",
            category: "design",
        },
        {
            name: "Inkscape",
            description: "برنامج الرسوم المتجهة المجاني",
            officialUrl: "https://inkscape.org",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Inkscape_logo.svg/1024px-Inkscape_logo.svg.png",
            icon: Palette,
            color: "bg-purple-50 text-purple-600 dark:bg-purple-900/20 dark:text-purple-300",
            category: "design",
        },
        {
            name: "Pencil2D",
            description: "برنامج الرسوم المتحركة ثنائية الأبعاد",
            officialUrl: "https://www.pencil2d.org",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Pencil2D_Logo.png/640px-Pencil2D_Logo.png",
            icon: Video,
            color: "bg-red-50 text-red-600 dark:bg-red-900/20 dark:text-red-300",
            category: "animation",
        },
    ],
    "web-development-intro": [
        {
            name: "Visual Studio Code",
            description: "محرر أكواد متقدم لتطوير الويب",
            officialUrl: "https://code.visualstudio.com",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png",
            icon: Code,
            color: "bg-blue-50 text-blue-600 dark:bg-blue-900/20 dark:text-blue-300",
            category: "programming",
        },
        {
            name: "Chrome DevTools",
            description: "أدوات مطوري الويب في متصفح كروم",
            officialUrl: "https://developers.google.com/web/tools/chrome-devtools",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Google_Chrome_icon_%28September_2014%29.svg/1024px-Google_Chrome_icon_%28September_2014%29.svg.png",
            icon: Globe,
            color: "bg-green-50 text-green-600 dark:bg-green-900/20 dark:text-green-300",
            category: "web",
        },
        {
            name: "Figma",
            description: "أداة تصميم واجهات المستخدم",
            officialUrl: "https://www.figma.com",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Figma-logo.svg/1200px-Figma-logo.svg.png",
            icon: Palette,
            color: "bg-pink-50 text-pink-600 dark:bg-pink-900/20 dark:text-pink-300",
            category: "design",
        },
    ],
    "app-development-intro": [
        {
            name: "Android Studio",
            description: "بيئة التطوير الرسمية لتطبيقات الأندرويد",
            officialUrl: "https://developer.android.com/studio",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Android_Studio_Icon_3.6.svg/1200px-Android_Studio_Icon_3.6.svg.png",
            icon: Smartphone,
            color: "bg-green-50 text-green-600 dark:bg-green-900/20 dark:text-green-300",
            category: "mobile",
        },
        {
            name: "Xcode",
            description: "بيئة التطوير لتطبيقات Apple",
            officialUrl: "https://developer.apple.com/xcode/",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Xcode_icon.png/1024px-Xcode_icon.png",
            icon: Smartphone,
            color: "bg-blue-50 text-blue-600 dark:bg-blue-900/20 dark:text-blue-300",
            category: "mobile",
        },
    ],
    "game-design-intro": [
        {
            name: "Unity",
            description: "محرك ألعاب احترافي متعدد الأنظمة",
            officialUrl: "https://unity.com",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Unity_2021.svg/1200px-Unity_2021.svg.png",
            icon: GameController2,
            color: "bg-gray-50 text-gray-600 dark:bg-gray-900/20 dark:text-gray-300",
            category: "games",
        },
        {
            name: "Blender",
            description: "برنامج النمذجة ثلاثية الأبعاد",
            officialUrl: "https://www.blender.org",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Blender_logo_no_text.svg/1200px-Blender_logo_no_text.svg.png",
            icon: Box,
            color: "bg-orange-50 text-orange-600 dark:bg-orange-900/20 dark:text-orange-300",
            category: "design",
        },
    ],
    "strategic-it": [
        {
            name: "Microsoft Project",
            description: "أداة إدارة المشاريع الاحترافية",
            officialUrl: "https://www.microsoft.com/project",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Microsoft_Project_2019_icon.svg/1200px-Microsoft_Project_2019_icon.svg.png",
            icon: FileText,
            color: "bg-indigo-50 text-indigo-600 dark:bg-indigo-900/20 dark:text-indigo-300",
            category: "management",
        },
        {
            name: "Microsoft Visio",
            description: "أداة رسم المخططات والرسوم البيانية",
            officialUrl: "https://www.microsoft.com/visio",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Microsoft_Visio_2019_icon.svg/1200px-Microsoft_Visio_2019_icon.svg.png",
            icon: Globe,
            color: "bg-blue-50 text-blue-600 dark:bg-blue-900/20 dark:text-blue-300",
            category: "diagramming",
        },
    ],
    "web-development-advanced": [
        {
            name: "Visual Studio Code",
            description: "محرر أكواد متقدم",
            officialUrl: "https://code.visualstudio.com",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png",
            icon: Code,
            color: "bg-blue-50 text-blue-600 dark:bg-blue-900/20 dark:text-blue-300",
            category: "programming",
        },
        {
            name: "Node.js",
            description: "بيئة تشغيل JavaScript للخادم",
            officialUrl: "https://nodejs.org",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Node.js_logo.svg/1200px-Node.js_logo.svg.png",
            icon: Code,
            color: "bg-green-50 text-green-600 dark:bg-green-900/20 dark:text-green-300",
            category: "backend",
        },
    ],
    "mobile-development": [
        {
            name: "Flutter",
            description: "إطار عمل لتطوير التطبيقات متعددة المنصات",
            officialUrl: "https://flutter.dev",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Google-flutter-logo.png/1024px-Google-flutter-logo.png",
            icon: Smartphone,
            color: "bg-blue-50 text-blue-600 dark:bg-blue-900/20 dark:text-blue-300",
            category: "mobile",
        },
        {
            name: "React Native",
            description: "إطار عمل لتطوير التطبيقات باستخدام React",
            officialUrl: "https://reactnative.dev",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1200px-React-icon.svg.png",
            icon: Smartphone,
            color: "bg-cyan-50 text-cyan-600 dark:bg-cyan-900/20 dark:text-cyan-300",
            category: "mobile",
        },
    ],
    "it-support-management": [
        {
            name: "Active Directory",
            description: "خدمة دليل مايكروسوفت لإدارة الشبكات",
            officialUrl: "https://learn.microsoft.com/windows-server/identity/ad-ds/get-started/ad-ds-overview",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Microsoft_Office_PowerPoint_%282019%E2%80%93present%29.svg/1200px-Microsoft_Office_PowerPoint_%282019%E2%80%93present%29.svg.png", // Mocking with a related MS icon as AD doesn't have a distinct public web logo usually
            icon: Shield,
            color: "bg-blue-50 text-blue-600 dark:bg-blue-900/20 dark:text-blue-300",
            category: "admin",
        },
        {
            name: "Windows Server",
            description: "نظام تشغيل الخوادم من مايكروسوفت",
            officialUrl: "https://www.microsoft.com/windows-server",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/1024px-Microsoft_logo.svg.png",
            icon: Monitor,
            color: "bg-gray-50 text-gray-600 dark:bg-gray-900/20 dark:text-gray-300",
            category: "server",
        },
    ],
    "game-development": [
        {
            name: "Unreal Engine",
            description: "محرك ألعاب متطور وقوي",
            officialUrl: "https://www.unrealengine.com",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Unreal_Engine_logo.svg/1200px-Unreal_Engine_logo.svg.png",
            icon: GameController2,
            color: "bg-black text-white dark:bg-gray-800",
            category: "games",
        },
        {
            name: "3ds Max",
            description: "برنامج النمذجة والرسوم المتحركة ثلاثية الأبعاد",
            officialUrl: "https://www.autodesk.com/products/3ds-max",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/3ds_Max_icon.png/600px-3ds_Max_icon.png",
            icon: Palette,
            color: "bg-blue-50 text-blue-600 dark:bg-blue-900/20 dark:text-blue-300",
            category: "design",
        },
    ],
    "cybersecurity": [
        {
            name: "Kali Linux",
            description: "توزيعة لاختبار الاختراق والأمن السيبراني",
            officialUrl: "https://www.kali.org",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Kali-linux-logo.svg/1200px-Kali-linux-logo.svg.png",
            icon: Shield,
            color: "bg-blue-50 text-blue-600 dark:bg-blue-900/20 dark:text-blue-300",
            category: "security",
        },
        {
            name: "Metasploit",
            description: "إطار عمل لاختبار الاختراق",
            officialUrl: "https://www.metasploit.com",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Metasploit_logo.png/640px-Metasploit_logo.png",
            icon: Shield,
            color: "bg-red-50 text-red-600 dark:bg-red-900/20 dark:text-red-300",
            category: "security",
        },
    ],
    "advanced-programming": [
        {
            name: "Visual Studio",
            description: "بيئة تطوير متقدمة لـ C# و VB.NET",
            officialUrl: "https://visualstudio.microsoft.com",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Visual_Studio_Icon_2022.svg/1200px-Visual_Studio_Icon_2022.svg.png",
            icon: Code,
            color: "bg-purple-50 text-purple-600 dark:bg-purple-900/20 dark:text-purple-300",
            category: "programming",
        },
        {
            name: "IntelliJ IDEA",
            description: "بيئة تطوير متقدمة لـ Java",
            officialUrl: "https://www.jetbrains.com/idea/",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/IntelliJ_IDEA_Icon.svg/1200px-IntelliJ_IDEA_Icon.svg.png",
            icon: Code,
            color: "bg-red-50 text-red-600 dark:bg-red-900/20 dark:text-red-300",
            category: "programming",
        },
    ],
    "it-project-management": [
        {
            name: "Jira",
            description: "أداة إدارة المشاريع البرمجية",
            officialUrl: "https://www.atlassian.com/software/jira",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Jira_%28Software%29_logo.svg/1200px-Jira_%28Software%29_logo.svg.png",
            icon: Wrench,
            color: "bg-blue-50 text-blue-600 dark:bg-blue-900/20 dark:text-blue-300",
            category: "management",
        },
        {
            name: "Trello",
            description: "أداة إدارة المهام والمشاريع",
            officialUrl: "https://trello.com",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Trello-logo.svg/1280px-Trello-logo.svg.png",
            icon: FileText,
            color: "bg-blue-50 text-blue-600 dark:bg-blue-900/20 dark:text-blue-300",
            category: "management",
        },
    ],
    "artificial-intelligence": [
        {
            name: "Google Colab",
            description: "بيئة تطوير الذكاء الاصطناعي السحابية",
            officialUrl: "https://colab.research.google.com",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Google_Colaboratory_SVG_Logo.svg/1200px-Google_Colaboratory_SVG_Logo.svg.png",
            icon: Brain,
            color: "bg-blue-50 text-blue-600 dark:bg-blue-900/20 dark:text-blue-300",
            category: "ai",
        },
        {
            name: "TensorFlow",
            description: "إطار عمل للتعلم العميق من جوجل",
            officialUrl: "https://www.tensorflow.org",
            logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Tensorflow_logo.svg/1200px-Tensorflow_logo.svg.png",
            icon: Brain,
            color: "bg-orange-50 text-orange-600 dark:bg-orange-900/20 dark:text-orange-300",
            category: "ai",
        },
    ],
}
