import {
    Shield,
    Stethoscope,
    Home,
    Heart,
    Activity,
    Smartphone,
    Laptop,
    Mail,
    Wifi,
    HardDrive,
    Monitor,
} from "lucide-react";
import {
    PostureIllustration,
    StretchIllustration,
    Rule202020Illustration,
    ErgonomicChairIllustration,
    WalkingIllustration,
    CarpalTunnelIllustration,
} from "./illustrations";

export const healthSections = [
    {
        id: "physical-safety",
        title: "السلامة الجسدية",
        subtitle: "Physical Safety",
        icon: Shield,
        gradient: "from-red-500 to-rose-500",
        glowColor: "rgba(239, 68, 68, 0.3)",
        accentBg: "bg-red-500/10",
        accentText: "text-red-400",
        accentBorder: "border-red-500/20",
        content: {
            intro: "تلتزم مؤسستنا بتوفير بيئة آمنة جسدياً لجميع طلاب BTEC، وتشمل سياساتنا:",
            points: [
                { title: "الفحص الطبي الدوري", desc: "يُطلب من جميع الطلاب إجراء فحص طبي شامل في بداية كل فصل دراسي للتأكد من لياقتهم البدنية وقدرتهم على المشاركة في جميع الأنشطة." },
                { title: "بروتوكولات الطوارئ", desc: "يتم تدريب جميع الموظفين على الإسعافات الأولية، مع توفر حقائب إسعاف في كل طابق وغرفة طوارئ مجهزة بالكامل." },
                { title: "سلامة المختبرات والورش", desc: "يجب ارتداء معدات الحماية الشخصية (PPE) في جميع المختبرات والورش العملية، مع إجراء تقييم المخاطر قبل كل نشاط عملي." },
                { title: "السلامة من الأجهزة الإلكترونية", desc: "فحص دوري لجميع الأجهزة الكهربائية والإلكترونية، والتأكد من سلامة الأسلاك والتوصيلات لمنع أي حوادث كهربائية." },
                { title: "الوقاية من الإصابات المتكررة", desc: "توفير كراسي ومكاتب مريحة تدعم وضعية الجسم الصحيحة، مع تشجيع الاستراحات المنتظمة أثناء العمل على الحاسوب." },
            ],
        },
    },
    {
        id: "health-guidance",
        title: "الإرشاد الصحي",
        subtitle: "Health Guidance",
        icon: Stethoscope,
        gradient: "from-blue-500 to-cyan-500",
        glowColor: "rgba(59, 130, 246, 0.3)",
        accentBg: "bg-blue-500/10",
        accentText: "text-blue-400",
        accentBorder: "border-blue-500/20",
        content: {
            intro: "نقدم خدمات إرشاد صحي شاملة تهدف إلى تعزيز صحة الطلاب:",
            points: [
                { title: "الإرشاد النفسي", desc: "يتوفر مرشد نفسي متخصص لمساعدة الطلاب في التعامل مع الضغوط الدراسية والمشاكل الشخصية بسرية تامة." },
                { title: "التغذية السليمة", desc: "برنامج توعوي عن أهمية التغذية المتوازنة وتأثيرها على التركيز والأداء الأكاديمي، مع توفير خيارات غذائية صحية في الكافتيريا." },
                { title: "النظافة الشخصية", desc: "حملات توعية دورية عن أهمية النظافة الشخصية والوقاية من الأمراض المعدية، خاصة في فترات الأوبئة." },
                { title: "إدارة الإجهاد", desc: "ورش عمل منتظمة لتعليم الطلاب تقنيات إدارة الإجهاد والتوتر مثل التنفس العميق والتأمل واليوغا." },
                { title: "النوم الصحي", desc: "إرشادات حول أهمية النوم الكافي (7-9 ساعات) وتأثيره على الأداء الأكاديمي والصحة العامة." },
            ],
        },
    },
    {
        id: "safe-environment",
        title: "بيئة دراسية آمنة",
        subtitle: "Safe Learning Environment",
        icon: Home,
        gradient: "from-emerald-500 to-green-500",
        glowColor: "rgba(16, 185, 129, 0.3)",
        accentBg: "bg-emerald-500/10",
        accentText: "text-emerald-400",
        accentBorder: "border-emerald-500/20",
        content: {
            intro: "نسعى لتوفير بيئة دراسية آمنة ومحفزة لجميع طلابنا:",
            points: [
                { title: "جودة الهواء والتهوية", desc: "أنظمة تكييف وتهوية حديثة في جميع القاعات الدراسية مع فلاتر HEPA لضمان جودة الهواء وصحة الجهاز التنفسي." },
                { title: "الإضاءة المناسبة", desc: "إضاءة طبيعية وصناعية متوازنة تقلل من إجهاد العين وتحسن التركيز، مع إمكانية التحكم في شدة الإضاءة." },
                { title: "مكافحة التنمر", desc: "سياسة صارمة ضد التنمر بجميع أشكاله (الجسدي، اللفظي، الإلكتروني) مع قنوات إبلاغ سرية وآمنة." },
                { title: "الأثاث المريح", desc: "كراسي ومكاتب بتصميم إرجونومي (Ergonomic) تدعم صحة الظهر والرقبة أثناء ساعات الدراسة الطويلة." },
                { title: "النظافة والتعقيم", desc: "جدول تنظيف وتعقيم يومي لجميع المرافق، مع توفير معقمات اليدين في كل قاعة ومختبر." },
            ],
        },
    },
    {
        id: "your-health-matters",
        title: "صحتك تهمنا",
        subtitle: "Your Health Matters",
        icon: Heart,
        gradient: "from-pink-500 to-fuchsia-500",
        glowColor: "rgba(236, 72, 153, 0.3)",
        accentBg: "bg-pink-500/10",
        accentText: "text-pink-400",
        accentBorder: "border-pink-500/20",
        content: {
            intro: "نضع صحة كل طالب في مقدمة أولوياتنا من خلال:",
            points: [
                { title: "الدعم للحالات المزمنة", desc: "خطط رعاية فردية للطلاب الذين يعانون من حالات صحية مزمنة مثل الربو، السكري، والحساسية مع تدريب الموظفين على التعامل معها." },
                { title: "الصحة النفسية أولاً", desc: "لا خجل من طلب المساعدة! نوفر جلسات دعم نفسي مجانية وخطوط مساعدة سرية متاحة على مدار الساعة." },
                { title: "التأمين الصحي", desc: "تغطية تأمين صحي شاملة لجميع الطلاب تشمل الحوادث والإصابات التي قد تحدث خلال الأنشطة الدراسية والعملية." },
                { title: "الكشف المبكر", desc: "فحوصات دورية للكشف المبكر عن مشاكل النظر والسمع والوضعية الجسدية التي قد تؤثر على التحصيل الدراسي." },
                { title: "خدمات الإحالة", desc: "شبكة إحالة متكاملة مع المستشفيات والمراكز الصحية القريبة لضمان حصول الطلاب على الرعاية المتخصصة عند الحاجة." },
            ],
        },
    },
    {
        id: "movement-awareness",
        title: "التوعية الحركية",
        subtitle: "Movement Awareness",
        icon: Activity,
        gradient: "from-amber-500 to-orange-500",
        glowColor: "rgba(245, 158, 11, 0.3)",
        accentBg: "bg-amber-500/10",
        accentText: "text-amber-400",
        accentBorder: "border-amber-500/20",
        content: {
            intro: "نشجع النشاط البدني وندمجه في الحياة الدراسية اليومية:",
            points: [
                { // Point 1: Stretch
                    title: "استراحات حركية",
                    desc: "فترات استراحة إجبارية كل 50 دقيقة تتضمن تمارين إطالة بسيطة لمكافحة آثار الجلوس المطول أمام الحاسوب.",
                    Illustration: StretchIllustration,
                },
                { // Point 2: Carpal Tunnel
                    title: "تمارين الوقاية",
                    desc: "تمارين مخصصة لمنع متلازمة النفق الرسغي (Carpal Tunnel) وآلام الظهر والرقبة الناتجة عن استخدام الحاسوب المطول.",
                    Illustration: CarpalTunnelIllustration,
                },
                { // Point 3: Walking (Sport Clubs or Walking?) Walking Illustration fits Walking point
                    title: "النوادي الرياضية",
                    desc: "أندية رياضية متنوعة (كرة قدم، سباحة، يوغا) متاحة لجميع الطلاب لتشجيع النشاط البدني المنتظم.",
                    // No specific illustration for generic sports yet, maybe none
                },
                { // Point 4: 20-20-20
                    title: "قاعدة 20-20-20",
                    desc: "كل 20 دقيقة أمام الشاشة، انظر إلى شيء يبعد 20 قدماً لمدة 20 ثانية لحماية عينيك من الإجهاد.",
                    Illustration: Rule202020Illustration,
                },
                { // Point 5: Walking
                    title: "المشي اليومي",
                    desc: "تشجيع المشي لمدة 30 دقيقة يومياً على الأقل، مع مسارات مشي مخصصة وآمنة داخل الحرم الجامعي.",
                    Illustration: WalkingIllustration,
                },
                { // Extra: Posture (Not in points but I should add it?) 
                    // I'll add a point for Posture because I have the illustration!
                    title: "وضعية الجلوس الصحيحة",
                    desc: "حافظ على استقامة ظهرك وتأكد من أن الشاشة في مستوى العين والقدمين مسطحتين على الأرض.",
                    Illustration: PostureIllustration
                },
                { // Extra: Ergonomic Chair
                    title: "أهمية الكرسي المريح",
                    desc: "استخدام كراسي قابلة للتعديل لدعم أسفل الظهر وتقليل الضغط على العمود الفقري.",
                    Illustration: ErgonomicChairIllustration
                }
            ],
        },
    },
];

export const securitySections = [
    {
        id: "2fa",
        title: "المصادقة الثنائية (2FA)",
        subtitle: "Two-Factor Authentication",
        icon: Smartphone,
        gradient: "from-violet-500 to-purple-500",
        glowColor: "rgba(139, 92, 246, 0.3)",
        accentText: "text-violet-400",
        tips: [
            "فعّل المصادقة الثنائية (2FA) على جميع حساباتك المهمة - البريد الإلكتروني، منصة الدراسة، وحسابات التواصل الاجتماعي.",
            "استخدم تطبيقات المصادقة مثل Google Authenticator أو Microsoft Authenticator بدلاً من رسائل SMS لأنها أكثر أماناً.",
            "احتفظ برموز الاسترداد (Recovery Codes) في مكان آمن غير إلكتروني في حال فقدت هاتفك.",
            "لا تشارك رموز التحقق مع أي شخص حتى لو ادعى أنه من الدعم الفني - هذه عملية تصيد.",
            "استخدم مفاتيح الأمان المادية (Security Keys) مثل YubiKey للحماية القصوى إن أمكن.",
        ],
    },
    {
        id: "device-safety",
        title: "أمان الأجهزة",
        subtitle: "Device Safety",
        icon: Laptop,
        gradient: "from-cyan-500 to-blue-500",
        glowColor: "rgba(6, 182, 212, 0.3)",
        accentText: "text-cyan-400",
        tips: [
            "أقفل جهازك دائماً عند مغادرة مكانك حتى لو لدقائق - استخدم Win+L في Windows أو Cmd+Ctrl+Q في Mac.",
            "حدّث نظام التشغيل والبرامج فوراً عند توفر تحديثات أمنية - التأخير يعرضك لثغرات معروفة.",
            "لا توصل USB أو أي جهاز تخزين غير معروف المصدر - قد يحتوي على برمجيات خبيثة.",
            "فعّل تشفير القرص الصلب (BitLocker على Windows أو FileVault على Mac) لحماية بياناتك إذا سُرق جهازك.",
            "استخدم برنامج مكافحة فيروسات محدث ولا تعطل جدار الحماية (Firewall) أبداً.",
            "احذر من شحن هاتفك عبر منافذ USB عامة (Juice Jacking) - استخدم شاحنك الخاص أو كابل شحن فقط.",
        ],
    },
    {
        id: "phishing",
        title: "التصيد الإلكتروني",
        subtitle: "Phishing Protection",
        icon: Mail,
        gradient: "from-red-500 to-rose-500",
        glowColor: "rgba(239, 68, 68, 0.3)",
        accentText: "text-red-400",
        tips: [
            "تحقق دائماً من عنوان المرسل - الرسائل المزيفة تستخدم عناوين مشابهة مثل support@g00gle.com بدل google.com.",
            "لا تنقر على روابط في رسائل غير متوقعة - مرر الماوس فوق الرابط أولاً لرؤية العنوان الحقيقي.",
            "لا تدخل بيانات تسجيل الدخول في صفحات وصلت إليها عبر رسالة بريد - ادخل الموقع مباشرة من المتصفح.",
            "كن حذراً من الرسائل العاجلة التي تطلب إجراء فوري مثل 'حسابك سيُغلق خلال 24 ساعة'.",
            "أبلغ فريق تكنولوجيا المعلومات فوراً عن أي رسالة مشبوهة تصلك على بريدك الجامعي.",
        ],
    },
    {
        id: "network-safety",
        title: "أمان الشبكات",
        subtitle: "Network Safety",
        icon: Wifi,
        gradient: "from-emerald-500 to-green-500",
        glowColor: "rgba(16, 185, 129, 0.3)",
        accentText: "text-emerald-400",
        tips: [
            "لا تتصل بشبكات Wi-Fi مفتوحة (بدون كلمة مرور) في الأماكن العامة - بياناتك قد تكون مكشوفة.",
            "استخدم VPN عند الاتصال بشبكات عامة لتشفير اتصالك وحماية بياناتك.",
            "تأكد أن المواقع تستخدم HTTPS (القفل الأخضر) قبل إدخال أي معلومات شخصية.",
            "عطّل خاصية الاتصال التلقائي بالشبكات المعروفة لمنع الاتصال بشبكات مزيفة بنفس الاسم.",
            "استخدم شبكة الجامعة الرسمية فقط للوصول إلى منصات الدراسة والموارد الأكاديمية.",
        ],
    },
    {
        id: "data-privacy",
        title: "خصوصية البيانات",
        subtitle: "Data Privacy",
        icon: HardDrive,
        gradient: "from-amber-500 to-orange-500",
        glowColor: "rgba(245, 158, 11, 0.3)",
        accentText: "text-amber-400",
        tips: [
            "لا تشارك معلوماتك الشخصية (رقم الهوية، العنوان، الصور) على منصات عامة أو مع أشخاص لا تعرفهم.",
            "راجع إعدادات الخصوصية في حساباتك على وسائل التواصل الاجتماعي واجعلها أكثر تقييداً.",
            "استخدم كلمات مرور مختلفة لكل حساب - استخدم مدير كلمات مرور مثل Bitwarden أو 1Password.",
            "احذف الحسابات والتطبيقات التي لا تستخدمها - كل حساب هو نقطة هجوم محتملة.",
            "قم بعمل نسخ احتياطية منتظمة لملفاتك الدراسية على خدمة سحابية مشفرة أو قرص خارجي.",
        ],
    },
    {
        id: "physical-digital",
        title: "السلامة الجسدية من الأجهزة",
        subtitle: "Physical Safety from Devices",
        icon: Monitor,
        gradient: "from-indigo-500 to-blue-500",
        glowColor: "rgba(99, 102, 241, 0.3)",
        accentText: "text-indigo-400",
        tips: [
            "اتبع قاعدة 20-20-20: كل 20 دقيقة، انظر لمسافة 20 قدم لمدة 20 ثانية لراحة عينيك.",
            "اضبط سطوع الشاشة ليتناسب مع إضاءة المحيط وفعّل فلتر الضوء الأزرق (Night Shift) في المساء.",
            "حافظ على وضعية جلوس صحيحة: الظهر مستقيم، القدمان مسطحتان على الأرض، الشاشة على مستوى العين.",
            "استخدم لوحة مفاتيح وماوس خارجيين مع اللابتوب لتقليل إجهاد المعصمين والرقبة.",
            "خذ استراحة لمدة 5-10 دقائق كل ساعة - قم وتحرك وأرح عينيك وجسمك.",
            "تأكد من سلامة كابلات الشحن والأجهزة الكهربائية لتجنب مخاطر الصدمة الكهربائية أو الحريق.",
        ],
    },
];
